import { useState, useEffect } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Separator } from '@/components/ui/separator';
import { Download, FileText, File, Loader2, FolderOpen, CheckCircle } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';
import { format } from 'date-fns';
import { ptBR } from 'date-fns/locale';
import type { Database } from '@/integrations/supabase/types';

type AnalysisStatus = Database['public']['Enums']['analysis_status'];

interface AgencyDocumentCenterProps {
  analysisId: string;
  analysisStatus: AnalysisStatus;
}

interface TermTemplate {
  id: string;
  name: string;
  description: string | null;
  file_name: string;
  file_path: string;
  file_size: number;
  created_at: string;
}

interface AnalysisDocument {
  id: string;
  file_name: string;
  file_path: string;
  file_size: number;
  file_type: string | null;
  created_at: string;
}

const AUTO_GENERATED_DOCS = [
  { 
    id: 'termo_garantia', 
    name: 'Termo de Garantia', 
    description: 'Documento principal com as condições da garantia locatícia',
    statuses: ['aprovada', 'aguardando_pagamento', 'ativo'] as AnalysisStatus[]
  },
  { 
    id: 'boleto_pagamento', 
    name: 'Boleto/Link de Pagamento', 
    description: 'Instruções de pagamento do Setup Fee',
    statuses: ['aguardando_pagamento'] as AnalysisStatus[]
  },
  { 
    id: 'ficha_cadastral', 
    name: 'Ficha Cadastral', 
    description: 'Resumo dos dados do inquilino e imóvel aprovados',
    statuses: ['aprovada', 'aguardando_pagamento', 'ativo'] as AnalysisStatus[]
  },
];

export function AgencyDocumentCenter({ analysisId, analysisStatus }: AgencyDocumentCenterProps) {
  const [termTemplates, setTermTemplates] = useState<TermTemplate[]>([]);
  const [analysisDocuments, setAnalysisDocuments] = useState<AnalysisDocument[]>([]);
  const [loading, setLoading] = useState(true);
  const [downloading, setDownloading] = useState<string | null>(null);

  useEffect(() => {
    const fetchDocuments = async () => {
      try {
        // Fetch term templates
        const { data: templates, error: templatesError } = await supabase
          .from('term_templates')
          .select('*')
          .eq('is_active', true)
          .order('name');

        if (templatesError) throw templatesError;
        setTermTemplates(templates || []);

        // Fetch analysis-specific documents
        const { data: docs, error: docsError } = await supabase
          .from('analysis_documents')
          .select('*')
          .eq('analysis_id', analysisId)
          .order('created_at', { ascending: false });

        if (docsError) throw docsError;
        setAnalysisDocuments(docs || []);
      } catch (error) {
        console.error('Error fetching documents:', error);
      } finally {
        setLoading(false);
      }
    };

    fetchDocuments();
  }, [analysisId]);

  const formatFileSize = (bytes: number) => {
    if (bytes < 1024) return `${bytes} B`;
    if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
    return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
  };

  const handleDownload = async (filePath: string, fileName: string, bucket: string) => {
    setDownloading(filePath);
    try {
      const { data, error } = await supabase.storage
        .from(bucket)
        .download(filePath);

      if (error) throw error;

      const url = URL.createObjectURL(data);
      const link = document.createElement('a');
      link.href = url;
      link.download = fileName;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
      
      toast.success('Download iniciado');
    } catch (error: any) {
      toast.error('Erro ao baixar arquivo: ' + error.message);
    } finally {
      setDownloading(null);
    }
  };

  const availableAutoGeneratedDocs = AUTO_GENERATED_DOCS.filter(doc => 
    doc.statuses.includes(analysisStatus)
  );

  if (loading) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="h-8 w-8 animate-spin text-primary" />
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Auto-generated documents (based on status) */}
      {availableAutoGeneratedDocs.length > 0 && (
        <Card className="border-primary/20">
          <CardHeader>
            <CardTitle className="text-base flex items-center gap-2">
              <CheckCircle className="h-4 w-4 text-primary" />
              Documentos Gerados
            </CardTitle>
            <CardDescription>
              Documentos gerados automaticamente após aprovação
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-3">
            {availableAutoGeneratedDocs.map((doc) => (
              <div
                key={doc.id}
                className="flex items-center justify-between p-3 rounded-lg border bg-muted/30 hover:bg-muted/50 transition-colors"
              >
                <div className="flex items-center gap-3">
                  <div className="p-2 rounded-lg bg-primary/10">
                    <FileText className="h-5 w-5 text-primary" />
                  </div>
                  <div>
                    <p className="font-medium text-sm">{doc.name}</p>
                    <p className="text-xs text-muted-foreground">{doc.description}</p>
                  </div>
                </div>
                <Button variant="outline" size="sm" disabled>
                  <Download className="h-4 w-4 mr-2" />
                  Em breve
                </Button>
              </div>
            ))}
            <p className="text-xs text-muted-foreground text-center pt-2">
              A geração automática de documentos estará disponível em breve.
            </p>
          </CardContent>
        </Card>
      )}

      {/* Analysis-specific uploaded documents */}
      {analysisDocuments.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle className="text-base flex items-center gap-2">
              <FolderOpen className="h-4 w-4" />
              Documentos da Análise
            </CardTitle>
            <CardDescription>
              Documentos enviados durante o processo de análise
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-2">
            {analysisDocuments.map((doc) => (
              <div
                key={doc.id}
                className="flex items-center justify-between p-3 rounded-lg border hover:bg-muted/30 transition-colors"
              >
                <div className="flex items-center gap-3">
                  <div className="p-2 rounded-lg bg-muted">
                    <File className="h-4 w-4 text-muted-foreground" />
                  </div>
                  <div>
                    <p className="font-medium text-sm">{doc.file_name}</p>
                    <p className="text-xs text-muted-foreground">
                      {formatFileSize(doc.file_size)} • {format(new Date(doc.created_at), 'dd/MM/yyyy', { locale: ptBR })}
                    </p>
                  </div>
                </div>
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => handleDownload(doc.file_path, doc.file_name, 'analysis-documents')}
                  disabled={downloading === doc.file_path}
                >
                  {downloading === doc.file_path ? (
                    <Loader2 className="h-4 w-4 animate-spin" />
                  ) : (
                    <Download className="h-4 w-4" />
                  )}
                </Button>
              </div>
            ))}
          </CardContent>
        </Card>
      )}

      <Separator />

      {/* Term templates from admin */}
      <Card>
        <CardHeader>
          <CardTitle className="text-base flex items-center gap-2">
            <FileText className="h-4 w-4" />
            Modelos e Termos Tridots
          </CardTitle>
          <CardDescription>
            Documentos padrão disponibilizados pela Tridots
          </CardDescription>
        </CardHeader>
        <CardContent>
          {termTemplates.length === 0 ? (
            <div className="text-center py-8 text-muted-foreground">
              <FileText className="h-12 w-12 mx-auto mb-3 opacity-30" />
              <p>Nenhum modelo disponível</p>
            </div>
          ) : (
            <div className="space-y-2">
              {termTemplates.map((template) => (
                <div
                  key={template.id}
                  className="flex items-center justify-between p-3 rounded-lg border hover:bg-muted/30 transition-colors"
                >
                  <div className="flex items-center gap-3">
                    <div className="p-2 rounded-lg bg-muted">
                      <FileText className="h-4 w-4 text-muted-foreground" />
                    </div>
                    <div>
                      <p className="font-medium text-sm">{template.name}</p>
                      {template.description && (
                        <p className="text-xs text-muted-foreground">{template.description}</p>
                      )}
                      <p className="text-xs text-muted-foreground">
                        {formatFileSize(template.file_size)}
                      </p>
                    </div>
                  </div>
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={() => handleDownload(template.file_path, template.file_name, 'term-templates')}
                    disabled={downloading === template.file_path}
                  >
                    {downloading === template.file_path ? (
                      <Loader2 className="h-4 w-4 animate-spin" />
                    ) : (
                      <Download className="h-4 w-4" />
                    )}
                  </Button>
                </div>
              ))}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
